version: '2'

services:
  website:
    build: .
    links:
      - db
    env_file:
      - '.env'
    expose:
      - 5000

  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: newuser
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: goalify

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - website
    volumes:
      - ./nginx/:/etc/nginx/:ro
